version: 2

sources:
  - name: business_data
    description: "Source datasets for purchase, product, and customer insights."
    schema: main
    tables:
      - name: customer_profile_dataset
        description: "Customer profile dataset containing demographic and preference data."
      - name: purchase_history_dataset
        description: "Purchase dataset with order and revenue details."
      - name: products_dataset
        description: "Product dataset with product descriptions and categories."
